services:
  - type: web
    name: inventariate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "flask db upgrade && gunicorn wsgi:app"
    envVars:
      - key: FLASK_APP
        value: wsgi.py

      # DATABASE_URL desde la DB de Render
      - key: DATABASE_URL
        fromDatabase:
          name: inventariate-db
          property: connectionString

      # SECRET_KEY seguro
      - key: SECRET_KEY
        generateValue: true

      # variables de AWS, sin valores en el repo
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: S3_BUCKET_NAME
        sync: false

databases:
  - name: inventariate-db
    databaseName: inventariate_db_roeq
    user: inventariate_db_roeq_user
    plan: free
